version: '3.9'

services:
  app:
    build:
      context: ./php
      dockerfile: Dockerfile

    container_name: php-service
    restart: always
    working_dir: /var/www
    volumes:
      - ../src:/var/www

  nginx:
    image: nginx:alpine
    container_name: nginx
    restart: always
    ports:
      - 8000:80
    volumes:
      - ./nginx:/etc/nginx/conf.d
      - ../src:/var/www

  mysql:
    image: mysql
    container_name: mysql-php
    restart: always
    volumes:
      - ./storage/mysql:/var/lib/mysql
      - ./mysql/mysql-init.sql:/docker-entrypoint-initdb.d/mysql-init.sql
    environment:
      MYSQL_ROOT_PASSWORD: root
    ports:
      - 3306:3306

  adminer:
    image: adminer
    restart: always
    ports:
      - 4000:8080
