version: '3.9'

services:
  app:
    build:
      context: ./php
      dockerfile: Dockerfile

    container_name: php-service
    restart: always
    working_dir: /var/www
    volumes:
      - ../src:/var/www

  nginx:
    image: nginx:alpine
    container_name: nginx
    restart: always
    ports:
      - 8000:80
    volumes:
      - ./nginx:/etc/nginx/conf.d
      - ../src:/var/www
